apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bwhv9gfgo-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:e8c46b89db7a7d8a81786b929e37269291c7c0e1@sha256:4cbaaa9f9950670133a730b2ecaba5dce448f1671a6c18df6a1f0180d2d0cf8c
          name: container-image
